name: Build and Deploy

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: "Install Node and Yarn"
        run: |
          ./mvnw --batch-mode -e --no-transfer-progress --fail-fast compile -P install-yarn -Dmaven.test.skip
      - name: "Copy static"
        run: |
          ./mvnw --batch-mode -e --no-transfer-progress --fail-fast prepare-package -Pbuild-public
      - name: "Build"
        run: |
          ./mvnw --batch-mode -e --no-transfer-progress --fail-fast package -Dmaven.test.skip
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
          file: Dockerfile
          tags: apache/dubbo-initializer:dev
          platforms: linux/amd64
